### ISSUE TITLE
echolocatoR singularity container

### ISSUE THREAD

**Issue by bschilder** [RajLabMSSM/echolocatoR#10]
Create a singularity container for echolocatoR to minimize installation issues.

**Comment by drkrynstrng** [comment]
Has anyone created a Singularity container image that could be distributed? It would definitely ease installation issues, especially on HPC clusters.

**Comment by bschilder** [comment]
Hi @drkrynstrng , thanks for the interest in echolocatoR! I haven't quite had a chance to make the singularity container just yet but this is definitely on my list and I'll be sure to let you know as soon as it's ready for release.

In the meantime, thanks for your patience and let me know if there's anything else I can help with!

**Comment by bschilder** [comment]
@drkrynstrng the official `echolocatoR` Docker/Singularity container is finally available! Sorry for the long wait, but there should be regular updates to it now that I have built into my GitHub Actions workflow.

See here for installation/usage instructions:
https://rajlabmssm.github.io/echolocatoR/articles/docker
