### ISSUE TITLE
Output installing latest echoverse version

### ISSUE THREAD

**Issue by AMCalejandro** [RajLabMSSM/echolocatoR#100]
Hi,

Just wanted to bring to your attention echoLD and echofinemap had non-zero exit status 

Code to install echoverse
`remotes::install_github("RajLabMSSM/echolocatoR@echoverse")`

Intallation output

![image](https://user-images.githubusercontent.com/84338703/188309674-59a843e8-09f1-472c-9f15-f8411fc09f44.png)

**Comment by bschilder** [comment]
Hey, so the echoverse branch is outdated now. All updates are being push to master.

So just use:

```R
remotes::install_github("RajLabMSSM/echolocatoR")

```

**Comment by bschilder** [comment]
Also, could you please include the full output from the installation messages? It looks like the photo you added is just the very end of it.
It may be that there's an issue with one of the dependencies for those subpackages, but I can't tell without the full messages.

**Comment by AMCalejandro** [comment]
Ok, although I have been trying to install both echoverse, and echolocatoR branches, I thought we still needed to install the echoverse branch. Thanks for clarifying.

I am currently trying to rerun the code to install echolocatoR outside the conda environment, as you mentioned in #102

**Comment by AMCalejandro** [comment]
Sorry, this has been me being clumsy. 

Your interpretation in #102 is correct. re-running the code to install and allowing to upgrade is enough.

**Comment by bschilder** [comment]
No worries, thanks for bearing with the growing pains.
I think once all of echolocatoR's functions are stable this should happen less frequently.
