### ISSUE TITLE
Conda Install Link Not Found

### ISSUE THREAD

**Issue by rootze** [RajLabMSSM/echolocatoR#123]
Hello, 
Thank you for making this package. 

I was trying to install the package thru Robust installation (conda).
https://rajlabmssm.github.io/echolocatoR/index.html 

## Link Broken

conda env create -f https://github.com/RajLabMSSM/echolocatoR/raw/master/inst/conda/echoR.yml
I got this error: 
### EnvironmentFileNotFound 

I wonder if you could update another link for conda installation. Thank you!

**Comment by bschilder** [comment]
Hi @rootze, 

Apologies, the website documentation is not yet fully updated. Please follow the README on the `echolocatoR` homepage instead:
https://github.com/RajLabMSSM/echolocatoR

`echolocatoR` now automatically installs the conda env as needed, so there's no longer a need to do it directly yourself. If you want an even more robust installation, please use the Docker/Singularity instructions here:
https://github.com/RajLabMSSM/echolocatoR#optional-dockersingularity

Best, 
Brian
