### ISSUE TITLE
Help me for this, I facd this error 

### ISSUE THREAD

**Issue by Nathan2598** [RajLabMSSM/echolocatoR#137]
ERROR: dependencies ‘echoannot’, ‘echofinemap’, ‘echoplot’ are not available for package ‘echolocatoR’
* removing ‘/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/echolocatoR’
Warning messages:
1: In i.p(...) :
  installation of package ‘/var/folders/f6/xxnk783n2414_dzlnq22157w0000gn/T//RtmpjcdFhe/file60d5bad69ed/XGR_1.1.9.tar.gz’ had non-zero exit status
2: In i.p(...) :
  installation of package ‘/var/folders/f6/xxnk783n2414_dzlnq22157w0000gn/T//RtmpjcdFhe/file60d6363f619/echoannot_0.99.11.tar.gz’ had non-zero exit status
3: In i.p(...) :
  installation of package ‘/var/folders/f6/xxnk783n2414_dzlnq22157w0000gn/T//RtmpjcdFhe/file60d6e7c9c6a/echofinemap_0.99.5.tar.gz’ had non-zero exit status
4: In i.p(...) :
  installation of package ‘/var/folders/f6/xxnk783n2414_dzlnq22157w0000gn/T//RtmpjcdFhe/file60d155c6025/echoplot_0.99.7.tar.gz’ had non-zero exit status
5: In i.p(...) :
  installation of package ‘/var/folders/f6/xxnk783n2414_dzlnq22157w0000gn/T//RtmpjcdFhe/file60d421e02e/echolocatoR_2.0.3.tar.gz’ had non-zero exit status

**Comment by bschilder** [comment]
a bit hard to assess without the info in the bug report template. also, it seems you only included a fraction of the message output, so I cant see what may have caused these downstream errors messages.

not much to go on here, but if i had to guess you're missing some of the dependencies. maybe from Bioconductor?

**Comment by Nathan2598** [comment]
I am trying to install echolocatoR and faced this issue/error and I don't know how to solve it.

**Comment by Nathan2598** [comment]
how to download the dependencies needed to install echoverse? in Bioconductor?

**Comment by bschilder** [comment]
please fill out the bug template. 
https://github.com/RajLabMSSM/echolocatoR/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=

without this information, I won't be able to help you very much. also, please include the full output from your console, not just the very end of it.
