### ISSUE TITLE
Error in Locus %in% loci : object 'Locus' not found

### ISSUE THREAD

**Issue by alexMarCar** [RajLabMSSM/echolocatoR#45]
I just set up echolocatoR according to the robust installation guideline.

When I call the finemap_loci function to check if echolocatoR can use all the packages properly:

r$> finemap_loci("echoR")                                                                            
[1] "+ CONDA:: Activating conda env 'echoR'"
[1] "Checking for tabix installation..."
[1] "Checking for bcftools installation..."
Error in Locus %in% loci : object 'Locus' not found

**Comment by bschilder** [comment]
Hi @alexMarCar, thanks for your interest in echolocatoR!

This error is happening because you need to provide the necessary inputs to `finemap _loci()`. I'd recommend you try out [the example vignettes](https://rajlabmssm.github.io/echolocatoR/articles/full_pipeline_vignette.html).
