### ISSUE TITLE
Plotting a specific window using PLOT.locus() function in EcholocatoR

### ISSUE THREAD

**Issue by bhuwankhatri11** [RajLabMSSM/echolocatoR#49]
How can I define a specific window for plotting using PLOT.locus() function in EcholocatoR package? For an instance I want to show only 167.35Mb-167.45Mb in the plot, and also have single lines of names of tissues/cell types from Roadmap.

**Comment by bschilder** [comment]
Have you tried subsetting the input data?

```R
min_pos <-  #<min position in bp>
max_pos <-  #<max position in bp>
finemap_DT_sub  <- subset(finemap_DT,  POS>=min_pos & POS<=max_pos)
```
