### ISSUE TITLE
Conda Installation Step 4 missing code

### ISSUE THREAD

**Issue by jackhump** [RajLabMSSM/echolocatoR#68]
```Install echolocatoR from command line so that it installs within the conda env:```

what do you suggest the user does here exactly?

**Comment by bschilder** [comment]
That just means; open R from the command line and install echolocatoR the usual way:
```R
if(!"remotes" %in% row.names(installed.packages())){install.packages("remotes")}

remotes::install_github("RajLabMSSM/echolocatoR")
```
