### ISSUE TITLE
echolocatoR for quantitative GWAS.

### ISSUE THREAD

**Issue by saifulislampharma** [RajLabMSSM/echolocatoR#70]
I am interested in applying  echolocatorR for quantitative train GWAS. But finemap_loci function requires "N_controls", "N_cases" to be specified, which I believe to be available for binary triat GWAS.
Could you kindly please suggest me whether echolocatoR can be applied for quantitative GWAS ? and if so, what will be the suitable values for "N_controls", "N_cases" ?
Thank you very much.

**Comment by bschilder** [comment]
Hi @saifulislampharma , 

Those columns are actually optional. echolocatoR uses them to infer total "N" if such a column does not already exist. Alternatively, you can supply a single value to the argument `finemap_loci(sample_size=)`.

Even in situations where certain columns are unavailable, echolocatoR will automatically check and report which fine-mapping tools you can and can't run given what data you've provided. 

Hope that helps!

-Brian

**Comment by saifulislampharma** [comment]
Hi  Brain,
Thank you very much for the clarification. I am closing it now. Thank you again.
