### ISSUE TITLE
Demo data: Error in `[.data.table`(y, x, nomatch = if (all.x) NA else NULL, on = by,  ........

### ISSUE THREAD

**Issue by michaelofrancis** [RajLabMSSM/echolocatoR#85]
I am still using the provided demo data (Nalls23andMe_2019). Now I am getting an error that looks like #6 or #47 ....however the solutions provided for those issues with people's own data should not apply to the demo data. Output/error log attached with sessionInfo():

[echolocatoR_log_MF_03162022.txt](https://github.com/RajLabMSSM/echolocatoR/files/8274173/echolocatoR_log_MF_03162022.txt)

****************************
Key error output:
Error in `[.data.table`(y, x, nomatch = if (all.x) NA else NULL, on = by,  : 
  logical error. i is not a data.table, but 'on' argument is provided.
Fine-mapping complete in:
Time difference of 1.8 mins
[1] "+ Identifying Consensus SNPs..."
[1] "++ support_thresh = 2"
[1] "++ top_CS_only=FALSE"
[1] "+ Calculating mean Posterior Probability (mean.PP)..."
Error in `[.data.table`(x, r, vars, with = FALSE) : 
  column(s) not found: SNP

**************************

Thanks!

**Comment by bschilder** [comment]
This should be resolved in the `echoverse` branch now. Note some of the argument names have been changed/deprecated, so you can try following this new (much shorter!) vignette:

### installation

```R
remotes::install_github("RajLabMMSM/echolocatoR@echoverse")
```


### example

```R
topSNPs <- echodata::topSNPs_Nalls2019
fullSS_path <- echodata::example_fullSS(dataset = "Nalls2019")

Nalls23andMe_2019.results <- echolocatoR::finemap_loci(
  fullSS_path = fullSS_path,
  topSNPs = topSNPs,
  loci = c("BST1","MEX3C"),
  dataset_name = "Nalls23andMe_2019",
  fullSS_genome_build = "hg19",
  bp_distance = 250000,
  munged = TRUE)
```
