### ISSUE TITLE
Munging full summary stats is way too slow

### ISSUE THREAD

**Issue by PhoebeGuo97** [RajLabMSSM/echolocatoR#93]
I'm try to munge my full summary stats by fullSS_path <- MungeSumstats::format_sumstats(path = fullSS_path, ref_genome = "GRCH37"). I left my MacBook on overnight and it's still running. 

The following is what I see in R Console:
First line of summary statistics file: 
uniqID.a1a2	CHR	BP	A1	A2	SNP	Z	P	Nsum	Neff	dir	EAF	BETA	SE	
Summary statistics report:
   - 13,367,299 rows
   - 13,354,030 unique variants
   - 2,394 genome-wide significant variants (P<5e-8)
   - 22 chromosomes
Checking for multi-GWAS.
Checking for multiple RSIDs on one row.
Checking SNP RSIDs.
11,599 SNP IDs are not correctly formatted. These will be corrected from the reference genome.
165,861 SNP IDs appear to be made up of chr:bp, these will be replaced by their SNP ID from the reference genome
Checking for merged allele column.
Checking A1 is uppercase
Checking A2 is uppercase
Ensuring all SNPs are on the reference genome.
Loading reference genome data.

**Comment by bschilder** [comment]
How long you expect this to take depends on your computer specs (part of the reason for the Issues template). Also, if you have an issue with `MungeSumstats`, you should submit it to the `MungeSumstats` repo:
https://github.com/neurogenomics/MungeSumstats
